### ISSUE TITLE
*sigh*

### ISSUE THREAD

**Issue by Cerealistic** [pickle69420/picklebox#4]
### Dude, seriously?
You do realize that bookmarklets are blocked at most **schools** and **organizations** right?

**Comment by pickle69420** [comment]
idc not every proxy works for everyone duh

**Comment by pickle69420** [comment]
most of the schools in my state at least (in the US) have them unblocked

**Comment by Cerealistic** [comment]
Dude, I live in Florida

**Comment by SnesLover22** [comment]
Yeah, this a bookmarklet for kids who can use bookmarklets. And if you don't like the project, screw you thats your problem. He can't change it. anyway maybe he'll turn it into a github page later on or something. But otherwise don't complain he's working hard. This project isn't for just you its for ANYBODY.

**Comment by Cerealistic** [comment]
I didn't say it was for me. I didn't say he wasn't working hard. Heck, I believe he stole some of my code to make this, he forked my repo yesterday.

**Comment by SnesLover22** [comment]
well you can't say that he stole it, since you had no license on the repo.

**Comment by Cerealistic** [comment]
Sorry for the misunderstanding, I should have licensed it lol. This guy also forked it out of spite, hence the about.

**Comment by SnesLover22** [comment]
lol

**Comment by pickle69420** [comment]
thanks @SnesLover22 and also i forked ur repo because u said not to fork it lmao

**Comment by SnesLover22** [comment]
which repo did you fork?
